protheus:
  restart: always
  build: .
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn protheus.wsgi:application -w 2 -b :8000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "8080:80"
  volumes:
    - /www/static
  volumes_from:
    - protheus
  links:
    - protheus:protheus
